### ISSUE TITLE
Implement CI and publish image to docker

### ISSUE THREAD

**Issue by ryanfobel** [ryanfobel/balena-conda#1]
https://forums.balena.io/t/building-and-publishing-to-docker-hub/5661

**Comment by ryanfobel** [comment]
The following GitHub Action will build a docker image whenever a new commit is pushed to the `main` branch and will push it to docker hub using the `latest` tag. This file

```yaml
name: build-image

on:
  push:
    # Only run workflow for pushes to specific branches
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Balena build docker image
        uses: ryanfobel/balena-cli-action@ce87e023391599a060db703f30e201ed680c81ca
        if: success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN}}
          balena_command: "build --deviceType raspberrypi4-64 --arch aarch64 --emulated"
          balena_secrets: |
            {
              "docker.pkg.github.com": {
                "username": "${{ secrets.MY_GITHUB_USER }}",
                "password": "${{ secrets.MY_GITHUB_TOKEN }}"
              }
            }
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ryanfobel --password-stdin
      - name: List the docker images
        run: docker image ls
      - name: Tag the Docker image
        run: docker tag workspace_main ryanfobel/raspberrypi4-64-conda:latest
      - name: Push the latest Docker image
        run: docker push ryanfobel/raspberrypi4-64-conda:latest
```

It may be worth migrating to the Docker-supported [buildx action](https://github.com/marketplace/actions/build-and-push-docker-images) instead of this custom `balena-cli-action`. Buildx also supports building docker containers for different architectures using QEMU and seems to be suitable for building balena containers as shown in these examples: [1](https://github.com/balenablocks/dashboard/blob/master/build-images.sh), [2](https://forums.balena.io/t/balena-push-via-github-actions/68084/8). The following command seemed to work on my Windows machine:

```sh
docker buildx build . --pull --build-arg BALENA_ARCH=aarch64 --platform=linux/arm64 --file Dockerfile.raspberrypi4-64 \
    --tag ryanfobel/raspberrypi4-64-conda --load
```
There are several Buildx-related GitHub Actions in the marketplace that are officially supported by Docker.
